services:
    # コンテナ名
    jupyterlab:
        build: .
        image: jupyterlab-test-img
        container_name: dev-jupyterlab2
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - "5555:5555"
        command:
            jupyter-lab --ip 0.0.0.0 --allow-root -b localhost